# Generated by Django 3.2.6 on 2021-09-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_user', models.CharField(blank=True, max_length=25, verbose_name='Telefono Usuario')),
                ('describe_user', models.TextField(blank=True, verbose_name='Perfil del Usuario')),
                ('linkedind_lnk', models.URLField(verbose_name='Url LinkedIn')),
                ('identidy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id Usuario')),
            ],
            options={
                'verbose_name': 'Datos del Usuario',
                'verbose_name_plural': 'Datos del Perfil',
            },
        ),
    ]
