# Generated by Django 3.2.6 on 2021-09-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datauser', '0004_auto_20210918_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='profesion_user',
            field=models.CharField(max_length=100, null=True, verbose_name='Profesión'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
